### PR TITLE
Refactor/img404error

### PR DESCRIPTION
**Pull request by Sulton88Mehron90**
### What does this PR do?
- [ ] Feature
- [ ] Bug fix
- [x] Refactor
- [ ] Other:

**Explain briefly:**
Update fallback image for missing park images
fyi: Handling the error gracefully in our application doesn't prevent the browser from logging the initial failed attempt to fetch the resource. 
---

### Does it break anything?
- [x] No
- [ ] Yes (describe: )

---

### Checklist
- [x] Code runs locally
- [x] All tests pass
- [x] Code is DRY / comments added where needed

---

### What's next?
[Test Error Handling](https://github.com/Marisa5280/stretchTech/issues/49)
[Add Route for a bad url](https://github.com/Marisa5280/stretchTech/issues/51)

### CODE REVIEW

**Review by jenziel — COMMENTED** [review]
These changes look great Parvin!  My only concern is the font on the bearError.png image.  I think the cursive might be hard for some people to read.

**Comment by Sulton88Mehron90** [comment]
you are right! Totally fixable!

**Comment by Sulton88Mehron90** [comment]
I switch to a more legible, font for better accessibility on the img. This will help ensure that the error message is clear and understandable to all users.
Screenshot 2023-09-13 at 8 18 08 AM
Screenshot 2023-09-13 at 8 16 19 AM

**Review by Marisa5280 — APPROVED** [review]
Love the bear image!

**Pull request merged**
